name: CedarCreekXC
favicon: null
layout_spectrum: 0.5428779514040798
typography_spectrum: 0.07732445956207812
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.9518333049491048
  lightness: 0.7746435075532645
  saturation: 0.3159142939839512
  rhythmicContrast: 0.7062194247264415
purpose: []
