name: CedarCreekXC
favicon: null
layout_spectrum: 0.5428779514040798
typography_spectrum: 0.93316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000190'
    - '#000092'
    - '#000092'
    - '#000099'
    - '#000091'
  brandStrength: 0.9518333049491048
  lightness: 0.7746435075532645
  saturation: 0.3159142939839512
  rhythmicContrast: 0.7062194247264415
purpose: []
